### ISSUE TITLE
javascript errors when adding certain dfi adresses

### ISSUE THREAD

**Issue by kuegi** [rogi-sh/defichain-income#10]
I am getting javascript errors as soon as I add this address. dH2Gqqy19ZF2qWDW9ySzfGxSGvtiXVBuAe

This address owns multiple vaults, some currently in liquidation. might that be the error?

![image](https://user-images.githubusercontent.com/29012906/146645477-94f15066-1448-4051-8bf4-56e8b3f771d4.png)

**Comment by rogi-sh** [comment]
thanks for report. fixed wirh 8.8.4
