### ISSUE TITLE
defichain-income.com Offline

### ISSUE THREAD

**Issue by hodlsolo** [rogi-sh/defichain-income#11]
Many thanks for the app and congrats on the recent growth!
https://www.defichain-analytics.com/community?entry=income

This is just a friendly heads-up that the stats on your site have been 'offline' for the past ~2 days.

![image](https://user-images.githubusercontent.com/86689668/147862071-6ed3111a-8587-431e-837e-fd65fd622a59.png)

Happy New Year! ... and thanks again.

**Comment by rogi-sh** [comment]
Api issues should be fine now
