### ISSUE TITLE
Mobile browsers - Magenta headline cutted at both ends

### ISSUE THREAD

**Issue by RoMi1981** [rogi-sh/defichain-income#18]
![Screenshot_20220914-092453_Chrome](https://user-images.githubusercontent.com/51130674/190088716-f7437646-2242-43ad-b194-0e09e8e76b0f.jpg)

Hi Igor,
on mobile browsers the magenta headline is cutted at both ends (left and right), it is also not scrolling. To read all information  i have to rotate the phone to landscape view.

Tested with:
- Google Chrome
- Firefox

OS: Android 12

Possible solutions:
- Headlinetext is scrolling (best solution, i think)
- Use smaller font
- use 2 lines

I already posted this issues some time ago in the defichain-income discord channel. You ment it shpuld scroll, but it doesn't.

Thank you for fixing and best regards.

You made such a awesome tool!!!!

**Comment by rogi-sh** [comment]
Headline is now scrollable with v10.0.5
