### ISSUE TITLE
More accurate handling of Cake freezer returns

### ISSUE THREAD

**Issue by RomanShumkov** [rogi-sh/defichain-income#8]
Could be as simple as configuring amount of frozen DFI on Cake and then adjusting auto-imported APY for each freezer option:

1. 5 year freezer - convert auto-imported APY to APR and boost by 50%
2. 10 year freezer - convert auto-imported APY to APR and boost by 100%
3. Sub 5 year freezer - convert auto-imported APY to APR and boost according to rebate scheme displayed on the website. I assume it won't change that often.

Thoughts?

**Comment by rogi-sh** [comment]
First of all defichain-income.com is focused on defichain users. So now we have 1 input where you cann add your stake amount. If you have many amounts in different freezer you can compute your own average apy on cake and overwrite the apy which is loaded from cake.

**Comment by RomanShumkov** [comment]
Fair enough if Cake use cases are not a priority :)
